"use strict";

function freezeArray(values) {
  return Object.freeze([...values]);
}

function freezeLoadout(loadout) {
  return Object.freeze({
    ...loadout,
    tags: freezeArray(loadout.tags ?? []),
    weaponFamilies: freezeArray(loadout.weaponFamilies ?? []),
    armorFamilies: freezeArray(loadout.armorFamilies ?? []),
    archetypes: freezeArray(loadout.archetypes ?? []),
    inventoryBias: Object.freeze({ ...(loadout.inventoryBias ?? {}) }),
    hotspots: freezeArray(loadout.hotspots ?? []),
  });
}

const PVP_LOADOUTS = Object.freeze({
  edge_main_melee: freezeLoadout({
    id: "edge_main_melee",
    label: "Edge Main Melee",
    tags: ["edge", "melee", "main"],
    weaponFamilies: ["whip", "dds", "dscim", "ags", "anchor", "dharok", "veracs", "dhalberd"],
    armorFamilies: ["fighter", "barrows", "rune", "granite", "mixed", "dharok"],
    archetypes: [
      "main_whip",
      "zerker_whip",
      "zerker_dscim",
      "ags_zerker",
      "ancient_gs_venge",
      "zerker_venge_ags",
      "zerker_whip_claws",
      "med_whip_ags",
      "full_dharok",
      "veracs_venge_claws",
      "obsidian_set_mauler",
      "dhalberd_venge_ags",
    ],
    inventoryBias: { food: 0.55, potions: 0.2, comboEat: 0.05 },
    hotspots: ["edge_ditch", "edge_south", "chaos_temple"],
  }),
  edge_ranged_melee: freezeLoadout({
    id: "edge_ranged_melee",
    label: "Edge Ranged/Melee",
    tags: ["edge", "hybrid", "range"],
    weaponFamilies: ["rune_cb", "msb", "dds", "dscim", "karils_cb", "blowpipe"],
    armorFamilies: ["dhide", "fighter", "rune", "skeletal", "mixed"],
    archetypes: [
      "msb_gmaul",
      "rcb_dds",
      "msb_dds",
      "dark_bow_ags",
      "zerker_dcb_ags",
      "med_dcb_claws",
      "void_dcb_claws",
      "void_dcb_ags",
      "void_ballista_ags",
      "ballista_pure",
      "karils_venge_ags",
      "blowpipe_venge_ags",
    ],
    inventoryBias: { food: 0.5, potions: 0.22, comboEat: 0.08 },
    hotspots: ["edge_ditch", "edge_south"],
  }),
  deep_wild_hybrid: freezeLoadout({
    id: "deep_wild_hybrid",
    label: "Deep Wild Hybrid",
    tags: ["deep", "hybrid", "risk"],
    weaponFamilies: ["ancients", "rune_cb", "staff", "dds", "spear", "sotd"],
    armorFamilies: ["mystic", "dhide", "ahrim", "skeletal"],
    archetypes: [
      "ancients_hybrid",
      "elite_ancients_dbow",
      "tribrid_main",
      "elite_nh_ags",
      "elite_nh_claws",
      "volatile_nh",
      "med_tribrid_ags",
      "nh_pure",
      "budget_nh_dds",
      "budget_nh_ags",
      "toxic_sotd_hybrid",
      "spear_tribrid_ags",
      "sotd_hybrid_claws",
    ],
    inventoryBias: { food: 0.4, potions: 0.28, comboEat: 0.12 },
    hotspots: ["mage_bank", "revs_entrance", "chaos_temple"],
  }),
  anti_pk_hybrid: freezeLoadout({
    id: "anti_pk_hybrid",
    label: "Anti-PK Hybrid",
    tags: ["anti", "hybrid", "escape"],
    weaponFamilies: ["staff", "rune_cb", "whip", "dds"],
    armorFamilies: ["dhide", "mystic", "tank", "skeletal"],
    archetypes: [
      "anti_pk_rcb",
      "anti_pk_whip",
      "budget_anti_pk",
      "budget_nh_dds",
      "med_tribrid_ags",
      "toxic_sotd_hybrid",
    ],
    inventoryBias: { food: 0.5, potions: 0.24, comboEat: 0.1 },
    hotspots: ["edge_south", "chaos_temple", "revs_entrance", "green_drags_gate"],
  }),
  budget_pk: freezeLoadout({
    id: "budget_pk",
    label: "Budget PK",
    tags: ["budget", "edge", "melee"],
    weaponFamilies: ["dscim", "rune_cb", "msb", "anchor"],
    armorFamilies: ["rune", "green_dhide", "granite", "mixed"],
    archetypes: ["budget_scim", "budget_rcb", "budget_msb"],
    inventoryBias: { food: 0.58, potions: 0.14, comboEat: 0.03 },
    hotspots: ["edge_ditch", "edge_south", "chaos_temple"],
  }),
  initiate_pure: freezeLoadout({
    id: "initiate_pure",
    label: "Initiate Pure",
    tags: ["edge", "pure", "initiate", "melee"],
    weaponFamilies: ["dscim", "dds", "gmaul", "msb"],
    armorFamilies: ["initiate", "mixed", "dhide"],
    archetypes: ["initiate_dscim_dds", "initiate_dscim_gmaul", "initiate_msb_gmaul"],
    inventoryBias: { food: 0.56, potions: 0.18, comboEat: 0.08 },
    hotspots: ["edge_ditch", "edge_south", "chaos_temple"],
  }),
  low_level_pure: freezeLoadout({
    id: "low_level_pure",
    label: "Low Level Pure",
    tags: ["edge", "pure", "low", "melee"],
    weaponFamilies: ["msb", "dds", "gmaul", "ags"],
    armorFamilies: ["dhide", "spined", "light", "mixed"],
    archetypes: [
      "low_level_dds_pure",
      "low_level_gmaul_pure",
      "low_level_msb_ags_pure",
      "msb_gmaul",
      "msb_dds",
    ],
    inventoryBias: { food: 0.54, potions: 0.18, comboEat: 0.1 },
    hotspots: ["edge_ditch", "edge_south", "chaos_temple"],
  }),
  rune_pure_members: freezeLoadout({
    id: "rune_pure_members",
    label: "Rune Pure Members",
    tags: ["edge", "pure", "rune", "mid"],
    weaponFamilies: ["dscim", "msb", "dds", "ags"],
    armorFamilies: ["rune", "fighter", "mixed", "dhide"],
    archetypes: [
      "rune_pure_dscim_dds",
      "rune_pure_msb_ags",
      "initiate_dscim_dds",
      "initiate_msb_gmaul",
    ],
    inventoryBias: { food: 0.54, potions: 0.18, comboEat: 0.08 },
    hotspots: ["edge_ditch", "edge_south", "chaos_temple"],
  }),
  void_pure: freezeLoadout({
    id: "void_pure",
    label: "Void Pure",
    tags: ["edge", "pure", "void", "risk"],
    weaponFamilies: ["msb", "ballista", "claws", "ags"],
    armorFamilies: ["void", "range"],
    archetypes: ["void_pure_claws", "void_pure_ballista", "ballista_pure"],
    inventoryBias: { food: 0.48, potions: 0.24, comboEat: 0.12 },
    hotspots: ["edge_ditch", "edge_south"],
  }),
  f2p_strength_pure: freezeLoadout({
    id: "f2p_strength_pure",
    label: "F2P Strength Pure",
    tags: ["edge", "f2p", "melee", "pure"],
    weaponFamilies: ["maple_shortbow", "rune_wh", "rune_baxe"],
    armorFamilies: ["green_dhide", "studded", "light"],
    archetypes: ["f2p_rwh_pure", "f2p_rbaxe_pure"],
    inventoryBias: { food: 0.64, potions: 0.08, comboEat: 0.0 },
    hotspots: ["varrock_ditch"],
  }),
  f2p_rune_pure: freezeLoadout({
    id: "f2p_rune_pure",
    label: "F2P Rune Pure",
    tags: ["edge", "f2p", "melee", "rune"],
    weaponFamilies: ["rune_scim", "rune_2h", "rune_baxe"],
    armorFamilies: ["rune", "green_dhide", "mixed"],
    archetypes: ["f2p_rscim_r2h", "f2p_rscim_rbaxe"],
    inventoryBias: { food: 0.62, potions: 0.08, comboEat: 0.0 },
    hotspots: ["varrock_ditch"],
  }),
  f2p_range_ko: freezeLoadout({
    id: "f2p_range_ko",
    label: "F2P Range KO",
    tags: ["edge", "f2p", "range", "ko"],
    weaponFamilies: ["maple_shortbow", "rune_2h", "rune_baxe"],
    armorFamilies: ["green_dhide", "studded", "leather"],
    archetypes: ["f2p_maple_r2h", "f2p_maple_rbaxe"],
    inventoryBias: { food: 0.62, potions: 0.08, comboEat: 0.0 },
    hotspots: ["varrock_ditch"],
  }),
  f2p_bind_pure: freezeLoadout({
    id: "f2p_bind_pure",
    label: "F2P Bind Pure",
    tags: ["edge", "f2p", "magic", "range"],
    weaponFamilies: ["staff", "maple_shortbow"],
    armorFamilies: ["wizard", "zamorak", "green_dhide"],
    archetypes: ["f2p_bind_blast", "f2p_bind_maple"],
    inventoryBias: { food: 0.58, potions: 0.06, comboEat: 0.0 },
    hotspots: ["varrock_ditch"],
  }),
  f2p_addy_pure: freezeLoadout({
    id: "f2p_addy_pure",
    label: "F2P Addy Pure",
    tags: ["edge", "f2p", "melee", "tank"],
    weaponFamilies: ["rune_scim", "rune_2h", "rune_baxe"],
    armorFamilies: ["adamant", "mixed"],
    archetypes: ["f2p_addy_r2h_tank", "f2p_addy_rbaxe_tank"],
    inventoryBias: { food: 0.6, potions: 0.08, comboEat: 0.0 },
    hotspots: ["varrock_ditch"],
  }),
  f2p_mage_pure: freezeLoadout({
    id: "f2p_mage_pure",
    label: "F2P Mage Pure",
    tags: ["edge", "f2p", "magic", "pure"],
    weaponFamilies: ["staff"],
    armorFamilies: ["wizard", "zamorak", "monk"],
    archetypes: ["f2p_fire_blast_pure", "f2p_wind_blast_pure"],
    inventoryBias: { food: 0.56, potions: 0.04, comboEat: 0.0 },
    hotspots: ["varrock_ditch"],
  }),
  f2p_bind_ko: freezeLoadout({
    id: "f2p_bind_ko",
    label: "F2P Bind KO",
    tags: ["edge", "f2p", "magic", "melee", "ko"],
    weaponFamilies: ["staff", "rune_2h", "rune_baxe"],
    armorFamilies: ["wizard", "zamorak", "monk"],
    archetypes: ["f2p_bind_r2h", "f2p_bind_rbaxe"],
    inventoryBias: { food: 0.58, potions: 0.06, comboEat: 0.0 },
    hotspots: ["varrock_ditch"],
  }),
  rusher: freezeLoadout({
    id: "rusher",
    label: "Rusher",
    tags: ["rush", "spec", "edge"],
    weaponFamilies: ["dds", "gmaul", "ags", "anchor"],
    armorFamilies: ["light", "fighter", "mixed"],
    archetypes: ["gmaul_rusher", "dds_rusher", "obby_rusher", "obby_mauler"],
    inventoryBias: { food: 0.44, potions: 0.16, comboEat: 0.14 },
    hotspots: ["edge_ditch", "edge_south"],
  }),
  edge_venge_zerker: freezeLoadout({
    id: "edge_venge_zerker",
    label: "Edge Venge Zerker",
    tags: ["edge", "melee", "zerker", "veng"],
    weaponFamilies: ["whip", "dscim", "dcb", "dds", "ags", "claws"],
    armorFamilies: ["fighter", "barrows", "rune", "mixed", "void"],
    archetypes: [
      "ancient_gs_venge",
      "zerker_venge_ags",
      "zerker_dcb_ags",
      "zerker_whip_claws",
      "veracs_venge_claws",
      "karils_venge_ags",
    ],
    inventoryBias: { food: 0.52, potions: 0.22, comboEat: 0.1 },
    hotspots: ["edge_ditch", "edge_south", "green_drags_gate"],
  }),
  edge_med_level: freezeLoadout({
    id: "edge_med_level",
    label: "Edge Med Level",
    tags: ["edge", "med", "hybrid", "veng"],
    weaponFamilies: ["whip", "dcb", "ags", "claws", "ancients", "blowpipe", "dhalberd"],
    armorFamilies: ["fighter", "barrows", "void", "dhide", "mystic", "mixed"],
    archetypes: [
      "med_whip_ags",
      "med_dcb_claws",
      "med_tribrid_ags",
      "blowpipe_venge_ags",
      "dhalberd_venge_ags",
    ],
    inventoryBias: { food: 0.48, potions: 0.24, comboEat: 0.12 },
    hotspots: ["edge_ditch", "edge_south", "revs_entrance"],
  }),
  edge_void_risk: freezeLoadout({
    id: "edge_void_risk",
    label: "Edge Void Risk",
    tags: ["edge", "void", "range", "hybrid"],
    weaponFamilies: ["dcb", "ballista", "claws", "ags"],
    armorFamilies: ["void", "dhide", "fighter"],
    archetypes: ["void_dcb_claws", "void_dcb_ags", "void_ballista_ags"],
    inventoryBias: { food: 0.46, potions: 0.24, comboEat: 0.12 },
    hotspots: ["edge_ditch", "edge_south"],
  }),
  edge_void_melee: freezeLoadout({
    id: "edge_void_melee",
    label: "Edge Void Melee",
    tags: ["edge", "void", "melee", "risk"],
    weaponFamilies: ["whip", "ags", "claws", "dcb"],
    armorFamilies: ["void", "fighter", "mixed"],
    archetypes: ["void_melee_claws", "void_melee_ags", "void_dcb_claws", "void_dcb_ags"],
    inventoryBias: { food: 0.48, potions: 0.24, comboEat: 0.12 },
    hotspots: ["edge_ditch", "edge_south"],
  }),
  edge_barrows_venge: freezeLoadout({
    id: "edge_barrows_venge",
    label: "Edge Barrows Venge",
    tags: ["edge", "barrows", "venge", "risk"],
    weaponFamilies: ["karils_cb", "veracs", "ags", "claws"],
    armorFamilies: ["barrows", "fighter", "mixed"],
    archetypes: ["karils_venge_ags", "veracs_venge_claws"],
    inventoryBias: { food: 0.5, potions: 0.22, comboEat: 0.1 },
    hotspots: ["edge_ditch", "edge_south", "green_drags_gate"],
  }),
  mid_tank: freezeLoadout({
    id: "mid_tank",
    label: "Mid Tank",
    tags: ["edge", "mid", "tank", "veng"],
    weaponFamilies: ["whip", "dcb", "ags", "staff"],
    armorFamilies: ["fighter", "granite", "rune", "mixed", "dhide"],
    archetypes: ["mid_tank_whip_ags", "mid_tank_dcb_ags", "toxic_sotd_hybrid"],
    inventoryBias: { food: 0.5, potions: 0.22, comboEat: 0.1 },
    hotspots: ["edge_ditch", "edge_south", "green_drags_gate", "chaos_temple"],
  }),
  edge_unorthodox_risk: freezeLoadout({
    id: "edge_unorthodox_risk",
    label: "Edge Unorthodox Risk",
    tags: ["edge", "unorthodox", "hybrid", "risk"],
    weaponFamilies: ["blowpipe", "dhalberd", "spear", "sotd", "ags", "claws"],
    armorFamilies: ["dhide", "barrows", "mystic", "mixed"],
    archetypes: [
      "blowpipe_venge_ags",
      "dhalberd_venge_ags",
      "obsidian_set_mauler",
      "spear_tribrid_ags",
      "sotd_hybrid_claws",
    ],
    inventoryBias: { food: 0.44, potions: 0.28, comboEat: 0.12 },
    hotspots: ["edge_ditch", "edge_south", "revs_entrance", "green_drags_gate"],
  }),
  deep_wild_nh: freezeLoadout({
    id: "deep_wild_nh",
    label: "Deep Wild NH",
    tags: ["deep", "nh", "hybrid", "risk"],
    weaponFamilies: ["ancients", "dcb", "staff", "ags", "claws"],
    armorFamilies: ["ahrim", "mystic", "dhide", "skeletal"],
    archetypes: [
      "elite_nh_ags",
      "elite_nh_claws",
      "volatile_nh",
      "tribrid_main",
      "elite_ancients_dbow",
      "toxic_sotd_hybrid",
      "spear_tribrid_ags",
      "sotd_hybrid_claws",
    ],
    inventoryBias: { food: 0.36, potions: 0.3, comboEat: 0.12 },
    hotspots: ["revs_entrance", "green_drags_gate"],
  }),
  deep_wild_budget_nh: freezeLoadout({
    id: "deep_wild_budget_nh",
    label: "Deep Wild Budget NH",
    tags: ["deep", "nh", "budget", "hybrid"],
    weaponFamilies: ["ancients", "rune_cb", "dark_bow", "dds"],
    armorFamilies: ["mystic", "dhide", "skeletal", "mixed"],
    archetypes: ["budget_nh_dds", "budget_nh_ags", "ancients_hybrid"],
    inventoryBias: { food: 0.44, potions: 0.26, comboEat: 0.09 },
    hotspots: ["revs_entrance", "green_drags_gate"],
  }),
  low_level_nh: freezeLoadout({
    id: "low_level_nh",
    label: "Low Level NH",
    tags: ["deep", "nh", "pure", "low"],
    weaponFamilies: ["ancients", "rune_cb", "dds", "staff"],
    armorFamilies: ["mystic", "dhide", "pure", "skeletal"],
    archetypes: ["low_level_nh_pure", "nh_pure", "budget_nh_dds"],
    inventoryBias: { food: 0.42, potions: 0.28, comboEat: 0.1 },
    hotspots: ["revs_entrance", "green_drags_gate", "chaos_temple"],
  }),
  deep_wild_staff_spec: freezeLoadout({
    id: "deep_wild_staff_spec",
    label: "Deep Wild Staff Spec",
    tags: ["deep", "nh", "magic", "risk"],
    weaponFamilies: ["volatile_staff", "toxic_sotd", "staff", "dcb"],
    armorFamilies: ["ahrim", "mystic", "dhide", "skeletal"],
    archetypes: ["volatile_nh", "toxic_sotd_hybrid", "sotd_hybrid_claws", "elite_nh_ags"],
    inventoryBias: { food: 0.34, potions: 0.32, comboEat: 0.12 },
    hotspots: ["revs_entrance", "green_drags_gate"],
  }),
});

const PVP_LOADOUT_IDS = Object.freeze(Object.keys(PVP_LOADOUTS));

function getPvpLoadout(loadoutId) {
  return PVP_LOADOUTS[loadoutId] ?? PVP_LOADOUTS.edge_main_melee;
}

function listPvpLoadouts() {
  return PVP_LOADOUT_IDS.map((loadoutId) => PVP_LOADOUTS[loadoutId]);
}

module.exports = {
  PVP_LOADOUT_IDS,
  PVP_LOADOUTS,
  getPvpLoadout,
  listPvpLoadouts,
};
